### ISSUE TITLE
OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by vizvasrj** [josephcappadona/m3u8downloader#1]
```
┌──(venv)─(root💀vizvasrj)-[/tmp]
└─# downloadm3u8 'https://b-g-eu-8.feetcdn.com:2223/v3-hls-playback/db0816de2695b28393c715545c03ed782c88d64cba262c90088373c65f351de347b0a719d205eeb6f0a50a4e7b74e3f6cd7d83686f2440e1033e3e1a766a3df361c276b29224498c212862870fe42bb4cffa08633ec0ad8647d1a21855d8cf72ed3c434575fceaeb3a91b1cedda64f07b6b648995a15fbf60be5236ac8038c98bf486a0e9c88a6e56d846f89fa13e3c2a93742dfed8c80c51cd87a77e96595b16faad3882487d3afb0cde73e91b75d46518810c9990239a6a4c76c261c39be05/720/index.m3u8' -o ./her.mp4
Traceback (most recent call last):
  File "/root/Github/venv/bin/downloadm3u8", line 8, in <module>
    sys.exit(main())
  File "/root/Github/venv/lib/python3.9/site-packages/m3u8downloader/main.py", line 507, in main
    downloader.start()
  File "/root/Github/venv/lib/python3.9/site-packages/m3u8downloader/main.py", line 270, in start
    self.download_m3u8_link(self.start_url)
  File "/root/Github/venv/lib/python3.9/site-packages/m3u8downloader/main.py", line 457, in download_m3u8_link
    self.process_media_playlist(url, content)
  File "/root/Github/venv/lib/python3.9/site-packages/m3u8downloader/main.py", line 402, in process_media_playlist
    self.media_playlist_localfile, _ = self.mirror_url_resource(url)
  File "/root/Github/venv/lib/python3.9/site-packages/m3u8downloader/main.py", line 312, in mirror_url_resource
    ensure_dir_exists_for(local_file)
  File "/root/Github/venv/lib/python3.9/site-packages/m3u8downloader/main.py", line 104, in ensure_dir_exists_for
    os.makedirs(os.path.dirname(full_filename), exist_ok=True)
  File "/usr/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 36] File name too long: '/root/.cache/m3u8downloader/her/v3-hls-playback/db0816de2695b28393c715545c03ed782c88d64cba262c90088373c65f351de347b0a719d205eeb6f0a50a4e7b74e3f6cd7d83686f2440e1033e3e1a766a3df361c276b29224498c212862870fe42bb4cffa08633ec0ad8647d1a21855d8cf72ed3c434575fceaeb3a91b1cedda64f07b6b648995a15fbf60be5236ac8038c98bf486a0e9c88a6e56d846f89fa13e3c2a93742dfed8c80c51cd87a77e96595b16faad3882487d3afb0cde73e91b75d46518810c9990239a6a4c76c261c39be05'
                                                                                

```

**Comment by josephcappadona** [comment]
Closed thanks to #2
